@token={{login.response.body.accessToken}}
# @name login
# Login user by email and password
POST http://localhost:3001/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "user@notfound.local",
  "password": "123456"
}

###

# Create a new user
POST http://localhost:3001/api/user/register HTTP/1.1
Content-Type: application/json

{
  "email": "user2@notfound.local",
  "name": "Keks",
  "password": "123456"
}

###

# Get user by ID
GET http://localhost:3001/api/user/64f204b187b8f055bac82c78 HTTP/1.1
Authorization: Bearer {{token}}
###

