# Create a new comment
POST http://localhost:3005/api/comments HTTP/1.1
Content-Type: application/json

{
  "message": "Автомобили",
  "postId": 1,
  "userId": "1"
}

###

# Delete comment by id
DELETE http://localhost:3005/api/comments/2 HTTP/1.1

###

# Get comments by post id
GET http://localhost:3005/api/comments?sortDirection=desc&postId=2&limit=50&page=1 HTTP/1.1

###

# Get comment by id
GET http://localhost:3005/api/comments/1 HTTP/1.1

###

# Update the comment by id
PATCH http://localhost:3005/api/comments/1 HTTP/1.1
Content-Type: application/json

{
  "message": "Другой комментарий"
}


###
